### ISSUE TITLE
RPC errors / timeouts should lead to FAILURE terminationEnsure that RPC timeouts

### ISSUE THREAD

**Issue by tilsche** [metricq/metricq-python#11]
See also https://github.com/metricq/metricq/issues/29

Especially make sure this works for timeouts from a reconnect -> register.

**Comment by tilsche** [comment]
As we discussed, we focus on the calls of RPCs and detect errors / timeouts there and cause shutdown.

**Comment by phijor** [comment]
I think by now, unhandled RPC errors correctly stop a Client.  We should close this and open more specific issues, e.g. if we encounter a client not stopping correctly.
