### ISSUE TITLE
Timedelta properties missing in documentation

### ISSUE THREAD

**Issue by bmario** [metricq/metricq-python#115]
https://metricq.github.io/metricq-python/api/misc.html#timedeltas-durations doesn't talk about the properties `s`, `ms`, `us` and `ns`.

**Comment by phijor** [comment]
But it... does?

https://metricq.github.io/metricq-python/api/misc.html#metricq.Timedelta.ms

**Comment by bmario** [comment]
Well, haven't seen it earlier 🤔 

nvm. than, I guess
