### ISSUE TITLE
Improve datatime parsing of Timestamp

### ISSUE THREAD

**Issue by bmario** [metricq/metricq-python#125]
It would be nice to allow users to only specifiy dates in metircq.Timestamp. For example:

- `metricq.Timestamp.from_date("2022-08-01")`
- `metricq.Timestamp.from_iso8601("2022-08-01T01:23")`

**Comment by tilsche** [comment]
The problem with these timestamps is that they are without timezone information, i.e., naive. So we must treat them as localtime with the respective issues (system setting dependency, DST ambiguity). It's an easy fix ([a362ced](https://github.com/metricq/metricq-python/commit/a362ced639bab7a4ac6fe20cee7aa76fba835851)), but do we want it?

**Comment by tilsche** [comment]
We decided to keep the functionality as is but give a proper error message for naive strings.
