### ISSUE TITLE
Allow `url` instead of `management_url` kwarg in `metricq.Client`

### ISSUE THREAD

**Issue by bmario** [metricq/metricq-python#130]
While it is technically correct, library users usually do not interact with the different connections. To reduce confusion and make user code shorter, we should consider to rename the `management_url` to `url` in the `metricq.Client` constructor. Maybe, we should also force only kwargs.

So this:
```
metricq.HistoryClient(token=token, management_url=server)
```

would become this in examples:

```
metricq.HistoryClient(token=token, url=server)
```

**Comment by tilsche** [comment]
I generally agree, but that is a really nasty breaking change where we probably have to have a transition phase with deprecation.

**Comment by bmario** [comment]
Actually, it isn't really breaking. The `management_url` is only used in `metricq.Agent`. And I feel like it should stay that way in that class, but we could have something like this in the `metricq.Client` constructor:

```
def __init__(self, *args, url: str = None, **kwargs):
    kwargs.setdefault("management_url", url)
    super().__init__(*args, **kwargs)
