### ISSUE TITLE
Incorrect iso8601 timestamp string parsing

### ISSUE THREAD

**Issue by apurvkulkarni7** [metricq/metricq-python#141]
Incorrect parsing while using ``metricq.Timestamp.from_iso8601`
It adds an hour to the provided string.

```python
    >>> metricq.__version__
    '3.1.1'
    >>> print(metricq.Timestamp.from_iso8601("2023-02-16T02:47:03.0Z"))
    [1676515623000000000] 2023-02-16 03:47:03+01:00

**Comment by bmario** [comment]
I believe it is working as intended. ISO8601 strings are time zone aware. Your input string is in `Z`, aka UTC or `+00:00`. The output is in `+01:00`, presumably your local time zone, hence the difference in the hours.

**Comment by tilsche** [comment]
Yes, this looks correct and as per the documentation.

`__str__` just  gives you "a human-readable date-time string *in the local timezone*". (See also [`datetime.astimezone`](https://docs.python.org/3/library/datetime.html#datetime.datetime.astimezone).

You can use `Timestamp.datetime` to get an aware `datetime` object to do any kind of custom formatting.

Do you think there is any addition to the documentation needed to clarify this?

**Comment by apurvkulkarni7** [comment]
Thank everyone. I am satisfied with the explanation. My bad for not paying close attention to the documentation. I seems we can close this issue.
