### ISSUE TITLE
Setup Fails, in protobuf version 27.3

### ISSUE THREAD

**Issue by floork** [metricq/metricq-python#194]
### Issue Summary:
In certain versions of `protobuf` (tested on 27.3), the installation process for the `metricq-python` package fails due to the version chosen by the setup.py (`protobuf<3.4,>=3.3`).

Manually updating the `protobuf` requirement to `protobuf<4.22,>=4.21` resolves the issue and allows the package to be installed correctly.

### Steps to Reproduce:
1. Set up an environment with `protobuf` version 27.3 installed.
   ```bash
   protoc --version
   libprotoc 27.3
   ```
2. Run the following command:
   ```bash
   pip install -e '.[dev]'
   ```
3. The installation fails when building the `protobuf` wheel, as shown in the error message.

### Observed Error:
The installation process produces the following error:
```plaintext
ImportError: cannot import name 'build_py_2to3' from 'distutils.command.build_py'
```

This occurs due to the outdated version of `protobuf` being pulled in (version 3.3.0), which is incompatible with modern build systems.

### Workaround:
Update the system so that `protobuf` 28 is installed:
```bash
protoc --version
libprotoc 28.0
```

**Comment by floork** [comment]
Up on closer inspection it still uses the wrong version after the update, even doe its building (but stuff like `tox` do not work with this version and would need a higher major version, so 5)

**Comment by bmario** [comment]
The usual protobuf stinks.

Seems like 5.26 bumped the major version again, hence a new version tuple is needed here:
 
https://github.com/metricq/metricq-python/blob/master/setup.py#L118
