### ISSUE TITLE
Protobuf dependency pip thingy?

### ISSUE THREAD

**Issue by bmario** [metricq/metricq-python#26]
The empire strikes again:

I just ran `pip install` in metricq-grafana, but got this message:

```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

metricq 1.2.0 requires protobuf~=3.12.0, but you'll have protobuf 3.13.0 which is incompatible.
```

**Comment by tilsche** [comment]
So, I stumped across this again because [some package](https://github.com/metricq/metricq-grafana/commit/bb5506eb1f43a2af2576275431071a161dc8efeb) depended on `protobuf` without a version, and that messes things up. But without, we should have this under control by now.
