### ISSUE TITLE
Improve handling of disconnects

### ISSUE THREAD

**Issue by bmario** [metricq/metricq-python#50]
Several issues surfaced with the current state of disconnect handling.

- Turns out, aio-pika `RobustConnection` is to robust for our use-case
- The ConnectionWatchdog isn't properly shutting down every bit of the Connection when the `connection_timeout` is reached, which may lead to clients ending in an undead state
- We need a better way to inform the clients that the connection to metricq is considered dead

Some ideas to workaround some of these issues for now:

- To somehow shutdown a hanging client, create a task, which `await`s the `stopped` method of a sink, can be used as a trigger. repsonding with e.g., `sys.exit(1)`. The method will throw the exception, which caused the shutdown.
- In an ideal world, we like to have a `metricq.Connection` This class should be aware of all required connections (management and data), the (re)connect timouts, and the combined state of the connections.
- We may consider replacing the `on_data` callbacks (and callbacks in general) with something more fancy, like generators. That way, clients could use the state of the returned futures / tasks to infer the state of the connection.

**Comment by tilsche** [comment]
This should be fixed with 5.0 and the update of aio-pika.
