### ISSUE TITLE
Consider declaring queues as "auto-delete" for transient sinks

### ISSUE THREAD

**Issue by phijor** [metricq/metricq-python#67]
If a `Sink` dies between subscribing and starting to consume metrics, its data queue will not get deleted and starts collecting metric data that is never consumed.

Consider adding an `auto-delete` to the queue (or something similar) so that this does not happen. At least for `Sink`s that are short lived are not expected to reuse their data queue after a reconnect.

**Comment by bmario** [comment]
The queues are already declared as auto-delete, but that doesn't help. 

> Auto-delete (queue that has had at least one consumer is deleted when last consumer unsubscribed)

What we need is a [queue-TTL](https://www.rabbitmq.com/ttl.html#queue-ttl).

**Comment by phijor** [comment]
We decided to have the manager use a queue TTL by default when declaring Sink data queues.

This is being implemented in https://github.com/metricq/metricq-manager/pull/38.

**Comment by phijor** [comment]
Closed via #38.
