### ISSUE TITLE
Timestamps from iso strings

### ISSUE THREAD

**Issue by tilsche** [metricq/metricq-python#7]
The current `Timestamp.from_iso8601` provides only limited value. It takes a very narrow string and assumes UTC. It's also not properly documented.

I see a couple of options:

1. Use Python 3.7's `datetime.datetime.from_isoformat` (we are currently on 3.6). That's also rather limited:

> This does not support parsing arbitrary ISO 8601 strings - it is only intended as the inverse operation of datetime.isoformat(). A more full-featured ISO 8601 parser, dateutil.parser.isoparse is available in the third-party package dateutil.

2. Use the `dateutil` package for more fully featured parsing. Adds another dependency.

3. Deprecate the function at all and suggest users to use the appropriate mean to get a `datetime.datetime` from either 1. or 2. themselves. Will result in more convoluted client code.

Also in all three cases we might want to reconsider the naming as it differs from both underlying functions.

**Comment by phijor** [comment]
> 1. Use Python 3.7's `datetime.datetime.from_isoformat` (we are currently on 3.6). That's also rather limited:

Since c4937472cde220cec921e640a067627aed971efd, `metricq` requires at least Python 3.7. So [`fromisoformat`](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat) is available.

**Comment by tilsche** [comment]
While `dateutil` actually does support allow 9-digit fractions, the datetime object does not. So we would lose precision by truncation. This applies to any solution that has a `datetime` object inbetween. So short of implementing our own fully-featuresd iso8601 parser we are screwed anyway.

I suggest we go with 2) `dateutil`, but clearly document the loss in precision.

**Comment by tilsche** [comment]
We we consider 3) not to be a sensible option. I would not mind to drop the v2.0.0 milestone.

**Comment by tilsche** [comment]
We decided to go for 2)
