### ISSUE TITLE
Remove deprecated methods/behavior

### ISSUE THREAD

**Issue by phijor** [metricq/metricq-python#73]
With the step to `metricq==2.0`, we might want to think about removing some deprecated methods:

* History Client methods:
    https://github.com/metricq/metricq-python/blob/ea64e2af7c38b7765f3bc780c25f3c4ac01e660a/metricq/history_client.py#L591-L605

* Unpacking of `TimeAggregate`:
    https://github.com/metricq/metricq-python/blob/ea64e2af7c38b7765f3bc780c25f3c4ac01e660a/metricq/types.py#L551-L565

**Comment by tilsche** [comment]
Good point. I'm a little bit hesitant because the deprecated decorator was only introduced 3 months ago. And `history_metric_metadata` wasn't previously marked as deprecated. But overall I think it's good to remove now.

**Comment by tilsche** [comment]
Consensus: Yes.
