### ISSUE TITLE
Consider updating types of TimeAggregate.{integral,active_time}

### ISSUE THREAD

**Issue by phijor** [metricq/metricq-python#76]
This has been sitting in the code as a TODO:

https://github.com/metricq/metricq-python/blob/8e73ceb203a70f5ae8093c218e1eb11f934ea93a/metricq/types.py#L545-L550

Tracking here for visibility.

**Comment by tilsche** [comment]
I'm happy to change `active_time` to `Timedelta`. This is the kind of breaking change I like for v2.0.0

`integral` is different, changing the unit, but not the type is one of the most evil things you can do when breaking the API. Even I don't hate user this much ;-). We can either

1) Add `integral_s`

2) *Also* deprecate `integral` and add `integral_ns`.
