### ISSUE TITLE
IntervalSource.period should be a Timedelta, not a float.

### ISSUE THREAD

**Issue by phijor** [metricq/metricq-python#81]
Here:

https://github.com/metricq/metricq-python/blob/61a3801890574373e8a8fd976d4808825cc41d15/metricq/interval_source.py#L78-L102

`IntervalSource._period` is alread a `Timedelta` internally, with the upgrade to 2.0 we might want the `period` property getter to return a `Timedelta` too.  The setter can stay "normalizing", i.e. continue to accept a number of seconds as a `float`, `int` etc.

**Comment by tilsche** [comment]
Also check in the setter that period is positive.
