### ISSUE TITLE
Improve the availability of the tools

### ISSUE THREAD

**Issue by bmario** [metricq/metricq-python#91]
The collection of tools is constantly growing. We should think about what to do with them. Possible solutions:

- Keep it as is
- Add them as entry_points
- Move them into separate/different repositories

**Comment by phijor** [comment]
I am in favour of moving them to a separate repository `metricq-tools`:

Pros:

* better availability (`pip install metricq-tools` and you are done)
* reduces dependency clutter (can remove the `[tools]` extra)
* optional entrypoints are almost impossible with setuptools (I tried before)
* we can reuse code between tools without needing to put it into `metricq`

The only downside I can currently think of is that developing a tool and new `metricq` features in tandem could be a bit more involved.  But one can always `pip install -e /path/to/metricq-dev-copy` in their local dev env, or install from a branch in CI.

**Comment by phijor** [comment]
[`metricq-tools`](https://github.com/metricq/metricq-tools) is a thing now :)
