### ISSUE TITLE
Sphix extension sphinx-autodoc-typehints 1.12.0 seems to be broken

### ISSUE THREAD

**Issue by phijor** [metricq/metricq-python#98]
Just got this error in a CI run:

https://github.com/metricq/metricq-python/runs/2351537093

58c087576a3019b2171f45b283256da7bce90147 pins it to a working version.
I'll just open this issue to keep track of it.

**Comment by phijor** [comment]
I opened an issue with the project: https://github.com/agronholm/sphinx-autodoc-typehints/issues/172.

**Comment by phijor** [comment]
Apparently this has been fixed (see https://github.com/tox-dev/sphinx-autodoc-typehints/issues/172#issuecomment-1007961727). Can someone in @metricq/core check out whether this resolves the issue for us? Ideally, reverting 58c0875 should make it work.

**Comment by bmario** [comment]
I totally consciously and deliberately fixed this in #119. Thanks for the hint.
